### ISSUE TITLE
Oversized Ripple Animations

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Buttons#3]
The ripple animations currently extend past the border of the button. I'm not sure how this can be fixed, but I'll probably find a way. Hopefully.

**Comment by TheAndroidMaster** [comment]
I've found a possible way to clip the ripple animations to the button shape using [`Paint.setXferMode`](https://developer.android.com/reference/android/graphics/Paint.html#setXfermode(android.graphics.Xfermode)), but it won't work for the outlined buttons. I might give each button style two different `Drawable`s - one for the background and one to clip the ripple animation. There is also the issue of possible `OutOfMemoryError`s since this method will involve the creation of an annoyingly large amount of `Bitmap`s...

**Comment by AdrianVovk** [comment]
Can't you just set one of the themes? Appcompat.borderless or something?
