### ISSUE TITLE
Make Ripples Change Position

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/Buttons#4]
Currently they only expand from the center of each button. The proper behavior would be to expand from wherever the button is touched. This might be somewhat difficult since the `TouchEvent` only specifies the x and y coordinates where the screen was touched - it doesn't account for the size of the view.

**Comment by jahirfiquitiva** [comment]
I think you can set a TouchEvent for an specific view. Won't it give you the coordinates in the view?

**Comment by TheAndroidMaster** [comment]
@jahirfiquitiva I think you can use `View.getLeft` and `View.getTop` (I googled it). Going to check it works first though, because I tried something similar earlier and it had a few issues.

**Comment by TheAndroidMaster** [comment]
Also I can't easily change the position of the ripple unless I want to start creating a new Bitmap for every frame in the animation, so it might take a while to finish.

**Comment by TheAndroidMaster** [comment]
To fix this I'm creating a new Bitmap in each frame - see #5.
